# Assignment 5 - Constraint Satisifaction Problems 

In this assignment you will solve the n-Queens problem using a constructive method and a replacement method. The n-Queens board requires you to place n queens on a board such that none of them are attacking the other by being on the same horizontal,vertical, or diagonal line. The constructive method starts from an empty board and requires you to fill in the queens. The iterative method will start with a random arrangement and require you to move them to solve it. 

In [2]:
import numpy as np
import random
from itertools import permutations
from itertools import combinations
from collections import deque

The following is the implementation of the N-Queens problem you will be using to solve the assignment. While you do not need to modify the implementation, it is important that you understand how the class functions.

In [3]:
class Stack:
    def __init__(self):
         self.stack = deque([])

    def isEmpty(self):
        return len(self.stack) == 0

    def push(self, item):
        self.stack.append(item)

    def pop(self):
        return self.stack.pop()

    def peek(self):
        return self.stack[-1]

    def size(self):
        return len(self.stack)
      
class NQueensBoard:
  
    def __init__(self, size=8, iterative=True):
        self.size = size
        if iterative:
            self.board = self.build_board(size)
        else:
            self.board = self.build_board_constructive(size)

    def build_board(self, size):
        """ 
        This method returns an empty board of size N.
        """
        
        board = np.zeros((size, size))
        return board

    def apply_placement(self, coord):
        """ 
        This method marks a coordinate on the board as having a Queen.
        """
        
        self.board[coord[0], coord[1]] = 1
        return self.board

    def examine_placement(self, board, coord):
        """ 
        This method marks a coordinate on a copy of the given board as 
        having a Queen. This is useful when you want to see what a board
        would look like after having made a move.
        """
        
        board2 = board.copy()
        board2[coord[0], coord[1]] = 1
        return board2

    def get_available_moves(self, board):
        """ 
        This method returns a list of legal moves (i.e., coordinates) 
        on the given board.
        """
        coords = np.asarray(board == 0).nonzero()
        coords = np.stack((coords[0], coords[1]), 1)
        coords = np.reshape(coords, (-1, 2))
        moves = []
        for coord in coords:
            if self.is_legal(board, coord):
                moves.append(coord)
        return moves

    def is_legal(self, board, coords):
        """ 
        This method returns True if a Queen may be placed at a given
        coordinate on a given board and False otherwise.
        """
        
        row, col = coords[0], coords[1]
        if np.sum(board[row, :]) != 0:
            return False
        if np.sum(board[:, col]) != 0:
            return False
        if np.sum(np.diagonal(board, offset=col - row, axis1=0, axis2=1)) != 0:
            return False
        if np.sum(np.diagonal(np.fliplr(board), offset=self.size - col - row - 1, axis1=0, axis2=1)) != 0:
            return False
        return True

    def build_board_constructive(self, n):
        """ 
        This method returns a randomly populated board of given size N.
        """
        
        board = np.zeros((n, n))
        cols = [i for i in range(n)]
        random.shuffle(cols)
        for i in range(n):
            board[i, cols[i]] = 1
        return board

    def get_moves_constructed(self, board):
        p1 = []
        moves = []
        for i in range(self.size):
            cols = [j for j in range(i, self.size)]
            a = np.where(board[i, :])
            p1.append([i, a[0][0]])
        return list(combinations(p1, 2))

    def apply_move_constructed(self,  board,move):
        board1 = board.copy()
        loc1 = move[0]
        loc2 = move[1]
        board1[loc1[0], loc1[1]] = 0
        board1[loc2[0], loc2[1]] = 0
        board1[loc1[0], loc2[1]] = 1
        board1[loc2[0], loc1[1]] = 1
        return board1

    def is_goal_state(self, board):
        """ 
        Use this method to check if the problem is solved.
        """
        
        # Check that the correct number of Queens are on the board.
        if np.sum(board) != self.size:
            return False
        # Check that each row and column contain at most one Queen.
        for i in range(self.size):
            if (np.sum(board[i, :]) > 1) or (np.sum(board[:, i] > 1)):
                print(np.sum(board[i, :])) 
                print(np.sum(board[:, i]))
                return False
        # Check that the diagonal tiles (running top left -> bottom right) have at most 1 Queen.
        for i in range(self.size):
            row, col = np.unravel_index(i, shape=(self.size, self.size))
            offset = abs(col - row)

            # Get the diagonal tiles offset by 0, 1, -1, 2, -2, etc. from
            # the center.
            diag1 = np.diagonal(board, offset=offset, axis1=0, axis2=1)
            diag2 = np.diagonal(board, offset=-offset, axis1=0, axis2=1)

            if (diag1.sum() > 1) or (diag2.sum() > 1):
                return False
        # Check that the diagonal tiles (running bottom left -> top right) have at most 1 Queen.
        for i in range(self.size):
            row, col = np.unravel_index(i, shape=(self.size, self.size))
            offset = abs(col - row)

            # Get the diagonal tiles offset by 0, 1, -1, 2, -2, etc. from
            # the center.
            diag1 = np.diagonal(np.fliplr(board), offset=offset, axis1=0, axis2=1)
            diag2 = np.diagonal(np.fliplr(board), offset=-offset, axis1=0, axis2=1)

            if (diag1.sum() > 1) or (diag2.sum() > 1):
                return False
        return True

In [4]:
# Create and visualize an empty 8x8 board.
n_queens = NQueensBoard(8, iterative=True)
print(n_queens.board)
n_queens.board

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
#TODO 1: Use a search algorithm to solve the problem for 1-2-3-4-8 Queens using get_available_moves() and examine_placement().

def dfs(board):
    ### TODO: START OF YOUR CODE ###
    board_set = set()
    search_stack = Stack()
    search_stack.push(board)
    while not search_stack.isEmpty():
        # print(search_stack.size())
        # print(len(board_set))
        current_board = search_stack.pop()
        if n_queens.is_goal_state(current_board):
            return current_board,len(board_set)
        elif str(list(current_board)) not in board_set:
            for each in n_queens.get_available_moves(current_board):
                next_board = n_queens.examine_placement(current_board,each)
                if str(list(next_board)) not in board_set:
                    search_stack.push(next_board)
            board_set.add(str(list(current_board)))

    # a node is said to have been 'expanded' when its
    # children have been added to the frontier
    ### TODO: END OF YOUR CODE ###
    raise Exception("Unreachable")
# Create and visualize a randomly populated 8x8 board.
print(dfs(n_queens.board))

(array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]]), 1969)


In [21]:
# Create and visualize a randomly populated 8x8 board.
n_queens2 = NQueensBoard(8, iterative=False)
print(n_queens2.board)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
#TODO: Use informed search to swap the queens using apply_moves_constructed() and get_moves_constructed().
class Queue:
    def __init__(self):
        self.queue = deque([])

    def isEmpty(self):
        return len(self.queue) == 0

    def push(self, item):
        self.queue.append(item)

    def pop(self):
        return self.queue.popleft()

    def peek(self):
        return self.queue[0]

    def size(self):
        return len(self.queue)

def heuristic(board):
    horizontal_cost_heuristic = 0
    diagonal_cost_heuristic = 0
    return_value = 0
    for i in range(0, n_queens2.size):
        for j in range(0, n_queens2.size):
            if board[i][j] == 1:
                horizontal_cost_heuristic = horizontal_cost_heuristic - 2
                for h in range(0, n_queens2.size):
                    if board[i][h] == 1:
                         horizontal_cost_heuristic = horizontal_cost_heuristic + 1
                    #Did not understand below vertical check.
                    if board[h][j] == 1:
                         horizontal_cost_heuristic =  horizontal_cost_heuristic + 1
                u = i + 1
                c = j + 1
                while u < n_queens2.size and c < n_queens2.size:
                    if board[u][c] == 1:
                         diagonal_cost_heuristic =  diagonal_cost_heuristic + 1
                    u = u + 1
                    c = c + 1
                u = i - 1
                c = j + 1
                while u >= 0 and c < n_queens2.size:
                    if board[u][c] == 1:
                         diagonal_cost_heuristic =  diagonal_cost_heuristic + 1
                    u = u - 1
                    c = c + 1
                u = i + 1
                c = j - 1
                while u < n_queens2.size and c >= 0:
                    if board[u][c] == 1:
                         diagonal_cost_heuristic =  diagonal_cost_heuristic + 1
                    u = u + 1
                    c = c - 1
                u = i - 1
                c = j - 1
                while u >= 0 and c >= 0:
                    if board[u][c] == 1:
                        heu_diagonal_cost =  diagonal_cost_heuristic + 1
                    u = u - 1
                    c = c - 1
    return_value = ( diagonal_cost_heuristic +  horizontal_cost_heuristic) / 2


    return int(return_value)

    # return 0
from itertools import count

unique = count()


def astar(board):
    ### TODO: START OF YOUR CODE ###

    # a node is said to have been 'expanded' when its
    # children have been added to the frontier

    from queue import PriorityQueue

    frontier = PriorityQueue()
    frontier.put((0, next(unique), board))

    expanded_set = set()

    while not frontier.empty():
        current_board = frontier.get()[2]
        if n_queens2.is_goal_state(current_board):
            return current_board, len(expanded_set)
        elif str(list(current_board)) not in expanded_set:
            # print(n_queens2.get_moves_constructed(current_board))
            for each in n_queens2.get_moves_constructed(current_board):
                next_board = n_queens2.apply_move_constructed(current_board, each)
                if str(list(next_board)) not in expanded_set:
                    frontier.put(( np.count_nonzero(next_board)+heuristic(
                        next_board), next(unique), next_board))
            expanded_set.add(str(list(current_board)))
            ### TODO: END OF YOUR CODE ###
    raise Exception("Unreachable")


end_board = astar(n_queens2.board)
print(end_board)


(array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]]), 13)
