In [2]:
import numpy as np
import heapq
from itertools import count

In [3]:
class Node():
  def __init__(self,value="A"):
    self.value=value
    self.children=[]
  def add_child(self,child,edge_weight=0):
    self.children.append((edge_weight,child))
    
class Stack:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[len(self.items)-1]
    self.items=self.items[:-1]
    return val

  def peek(self):
     return self.items[len(self.items)-1]

  def size(self):
     return len(self.items)
    
class Queue:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[0]
    self.items=self.items[1:]
    return val
      
  def peek(self):
     return self.items[0]

  def size(self):
     return len(self.items)

In [4]:
class tic_tac_toe_game():
  def __init__(self,n=3,print=False):
    self.size=n
    self.printing=False
    self.board=self.build_board(n)
    self.turn_number=0
    self.game_complete=0
  def build_board(self,n):
    board=np.zeros((n,n))
    return board
  def reset_board(self,n):
    self.board=np.zeros((n,n))
    self.turn_number=0

  def get_available_moves(self,board):
    coords=np.asarray(board==0).nonzero()
    coords=np.stack((coords[0],coords[1]),1)
    coords=np.reshape(coords,(-1,2))
    if (self.is_goal_state(board)!=0):
      return []
    return coords
      
  def is_move_legal(self,move,board):
    return board[move[0]][move[1]]==0
  def apply_move(self,move):
    #Move is legal
    if(self.turn_number % 2 ==0):
      self.board[move[0],move[1]]=1
    else:
      self.board[move[0],move[1]]=2
    self.turn_number=self.turn_number+1
  def examine_move(self,board,move,player):
    board2=board.copy()
    #Move is legal
    if(1):
      board2[move[0],move[1]]=player
    return board2
  def is_goal_state(self,board):
    #Will do in a second
   
    for i in range(3):
      if(np.all(board[i,:]==1) or np.all(board[:,i]==1) or np.all(np.diag(board)==1) or np.all(np.diag(np.fliplr(board))==1)):
        return 1
      if(np.all(board[i,:]==2) or np.all(board[:,i]==2)or np.all(np.diag(board)==2)or np.all(np.diag(np.fliplr(board))==2)):
        return -1
    if(np.sum(board)>5*1+4*2-1):
      return 0.1
    return 0
      

In [5]:
A=tic_tac_toe_game()

In [6]:
print(A.board)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
###TODO code the minimax algorithm and return the best move
#You will get a board,if you are maximizing
#def minimax_with_move(board,maximizing):
#Call examine move with (board,move,2-maximizing)
#I would recommend a helper function which returns the move while the main recursive call returns a move
def minimax(board, maximizing):
    origin_next_moves = list(A.get_available_moves(board))
    next_moves = []
    for each in origin_next_moves:
        next_moves.append(list(each))
    np.random.shuffle(next_moves)

    # value_dic = {}
    # for each in next_moves:
    #     # print("each",each)
    #     value_dic[(each[0], each[1])] = 0
    best_move =[[]]
    final_value = minimax_inner(board, maximizing, best_move, origin_next_moves)
    # print("final:",final_value)
    # print(best_move)
    # for key, value in value_dic.items():
    #     if value == final_value:
    #         result.append(key)
    # print(result)
    # return np.asarray(list(result[0]))
    return np.asarray(best_move[0])

def minimax_inner(board, maximizing, best_move, origin):
    if A.is_goal_state(board) != 0:  # means game over
        return A.is_goal_state(board)
    if maximizing == 1:  # it is the opponent's turn
        value = float("-inf")
        move_set = A.get_available_moves(board)
        np.random.shuffle(move_set)
        for each in move_set:
            # # print(next_moves)
            # next_moves.remove(each)
            next_board = A.examine_move(board,each,2-maximizing)
            mm = minimax_inner(next_board, 0, best_move, origin)
            if mm>value:
                best_move[0] = each
                # print(best_move)
            value = max(value,mm)
        return value
    else:  # it is my turn
        value = float("inf")
        move_set = A.get_available_moves(board)
        np.random.shuffle(move_set)
        for each in move_set:
            next_board = A.examine_move(board,each,2-maximizing)
            mm =  minimax_inner(next_board, 1,  best_move, origin)
            if mm<value:
                best_move[0] = each
                # print(best_move)
            value = min(value,mm)
        return value


In [8]:
A.reset_board(3)
print(A.board)

maximizing=1
#while(A.is_goal_state(A.board)==0):
#  val,move=minimax_with_move(A.board,maximizing)
#  A.apply_move(move)
#  print(A.board)

#  if(A.is_goal_state(A.board)==0):
#    val,move=minimax_with_move(A.board,1-maximizing)
#    A.apply_move(move)
#    print(A.board)

    
A.reset_board(3)
while(A.is_goal_state(A.board)==0):    
  moveset=A.get_available_moves(A.board)
  np.random.shuffle(moveset)   
  A.apply_move(moveset[0])
  print(A.board)
  if(A.is_goal_state(A.board)==0):
    move=minimax(A.board,1-maximizing)
    A.apply_move(move)
    print(A.board)   
   


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]


[[0. 0. 2.]
 [0. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 2.]
 [0. 0. 0.]
 [0. 1. 0.]]


[[1. 0. 2.]
 [0. 0. 2.]
 [0. 1. 0.]]
[[1. 1. 2.]
 [0. 0. 2.]
 [0. 1. 0.]]
[[1. 1. 2.]
 [0. 0. 2.]
 [0. 1. 2.]]


In [26]:
# To do: Convert minimax code to code with alpha beta pruning
def alpha_beta_pruning(board, maximizing):
    origin_next_moves = list(A.get_available_moves(board))
    next_moves = []
    for each in origin_next_moves:
        next_moves.append(list(each))
    np.random.shuffle(next_moves)

    # value_dic = {}
    # for each in next_moves:
    #     # print("each",each)
    #     value_dic[(each[0], each[1])] = 0

    alpha = float("-inf")
    beta = float("inf")
    best_move = [[]]
    final_value = alpha_beta_pruning_inner(board, alpha, beta, maximizing, best_move, origin_next_moves)
    # print("final:", final_value)
    # print(best_move[0])
    return best_move[0]


def alpha_beta_pruning_inner(board, alpha, beta, maximizing, best_move, origin):
    if A.is_goal_state(board) != 0:  # means game over
        return A.is_goal_state(board)
    if maximizing == 1:  # it is the opponent's turn
        value = float("-inf")
        next_moves = A.get_available_moves(board)
        np.random.shuffle(next_moves)
        for each in next_moves:
            # print(next_moves)
            next_board = A.examine_move(board, each, 2 - maximizing)
            ab = alpha_beta_pruning_inner(next_board, alpha, beta, 0, best_move, origin)
            if ab > value:
                best_move[0] = each
            value = max(value, ab)
            if value >= beta:
                return value
            alpha = max(alpha,value)
        return value
    else:  # it is my turn
        value = float("inf")
        next_moves = A.get_available_moves(board)
        np.random.shuffle(next_moves)
        for each in next_moves:
            # print(next_moves)
            next_board = A.examine_move(board, each, 2 - maximizing)
            ab = alpha_beta_pruning_inner(next_board, alpha, beta, 1, best_move, origin)
            if ab < value:
                best_move[0] = each
            value = min(value, ab)
            if value <= alpha:
                return value
            beta = min(value,beta)
        return value

# start game   
A.reset_board(3)

while (A.is_goal_state(A.board) == 0):
    maximizing = 1
    moveset = A.get_available_moves(A.board)
    np.random.shuffle(moveset)
    A.apply_move(moveset[0])
    print(A.board)

    if (A.is_goal_state(A.board) == 0):
        move = alpha_beta_pruning(A.board, 1 - maximizing)
        A.apply_move(move)
        print(A.board)


[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[2. 1. 0.]
 [0. 0. 1.]
 [0. 2. 0.]]
[[2. 1. 0.]
 [0. 0. 1.]
 [1. 2. 0.]]
[[2. 1. 0.]
 [0. 2. 1.]
 [1. 2. 0.]]
[[2. 1. 1.]
 [0. 2. 1.]
 [1. 2. 0.]]
[[2. 1. 1.]
 [0. 2. 1.]
 [1. 2. 2.]]
